#ifndef FAILURE_CODE_H
#define FAILURE_CODE_H

#define FAILURE_CODE_MAC_OWNER_1  (251)
#define FAILURE_CODE_MAC_OWNER_2  (482)
#define FAILURE_CODE_MAC_OWNER_3  (120)

#define FAILURE_CODE_ROM_TEST_1   (239)
#define FAILURE_CODE_ROM_TEST_2   (173)
#define FAILURE_CODE_ROM_TEST_3   (222)
#define FAILURE_CODE_ROM_TEST_4   (190)

#endif
